//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conhecimento
    {
        public long IDProgramador { get; set; }
        public int Ionic { get; set; }
        public int Reactjs { get; set; }
        public int Reactnative { get; set; }
        public int Android { get; set; }
        public int IOS { get; set; }
        public int HTML { get; set; }
        public int CSS { get; set; }
        public int Bootstrap { get; set; }
        public int Jquery { get; set; }
        public int AngularJS { get; set; }
        public string Outro { get; set; }
    
        public virtual Programador Programador { get; set; }
    }
}
