//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programador
    {
        public long IDProgramador { get; set; }
        public string EMail { get; set; }
        public string Nome { get; set; }
        public string Skype { get; set; }
        public long Telefone { get; set; }
        public string Linkedin { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public string DisponibilidadeTrabalho { get; set; }
        public string MelhorHorario { get; set; }
        public int Pretensao { get; set; }
    
        public virtual Conhecimento Conhecimento { get; set; }
    }
}
